# Generated by Django 6.0 on 2025-12-16 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('AnswerDate', models.DateTimeField(auto_now_add=True)),
                ('AnswerScore', models.IntegerField(default=0)),
                ('AnswerBody', models.TextField()),
                ('OwnUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-AnswerScore', 'AnswerDate'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=200)),
                ('Body', models.TextField()),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('AnswerCount', models.IntegerField(default=0)),
                ('FavoriteCount', models.IntegerField(default=0)),
                ('Closedate', models.DateField(blank=True, null=True)),
                ('AcceptAnswer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_by_question', to='app.answer')),
                ('OwnUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.question'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='TagItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.question')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='app.tags')),
            ],
            options={
                'unique_together': {('q_id', 'tag_id')},
            },
        ),
    ]
